# Generated by Django 2.1.2 on 2018-10-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181022_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='collegeid',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='collegeid'),
        ),
    ]
