# Generated by Django 2.1.2 on 2018-11-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181022_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='collegeid',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='collegeId'),
        ),
    ]
